CREATE TABLE IF NOT EXISTS DataBase_sql (
    `rtf1_ansi_ansicpg1252_cocoartf2706` VARCHAR(120) CHARACTER SET utf8,
    `Column_2` VARCHAR(12) CHARACTER SET utf8,
    `Column_3` VARCHAR(1) CHARACTER SET utf8
);
INSERT INTO DataBase_sql VALUES ('\\cocoatextscaling0\\cocoaplatform0{\\fonttbl\\f0\\fswiss\\fcharset0 Helvetica;}',NULL,NULL),
	('{\\colortbl;\\red255\\green255\\blue255;}',NULL,NULL),
	('{\\*\\expandedcolortbl;;}',NULL,NULL),
	('\\paperw11900\\paperh16840\\margl1440\\margr1440\\vieww28600\\viewh15360\\viewkind0',NULL,NULL),
	('\\pard\\tx566\\tx1133\\tx1700\\tx2267\\tx2834\\tx3401\\tx3968\\tx4535\\tx5102\\tx5669\\tx6236\\tx6803\\pardirnatural\\partightenfactor0',NULL,NULL),
	('\\f0\\fs24 \\cf0 CREATE TABLE users (\\',NULL,NULL),
	('    id INT PRIMARY KEY AUTO_INCREMENT','\\',NULL),
	('    username VARCHAR(255) UNIQUE','\\',NULL),
	('    email VARCHAR(255) UNIQUE','\\',NULL),
	('    password VARCHAR(255)','\\',NULL),
	('    first_name VARCHAR(255)','\\',NULL),
	('    last_name VARCHAR(255)','\\',NULL),
	('    created_at TIMESTAMP','\\',NULL),
	('    updated_at TIMESTAMP\\',NULL,NULL),
	(');\\',NULL,NULL),
	('\\',NULL,NULL),
	('CREATE TABLE vehicles (\\',NULL,NULL),
	('    id INT PRIMARY KEY AUTO_INCREMENT','\\',NULL),
	('    make VARCHAR(255)','\\',NULL),
	('    model VARCHAR(255)','\\',NULL),
	('    year INT','\\',NULL),
	('    mileage INT','\\',NULL),
	('    color VARCHAR(255)','\\',NULL),
	('    price DECIMAL(10','2)','\\'),
	('    created_at TIMESTAMP','\\',NULL),
	('    updated_at TIMESTAMP\\',NULL,NULL),
	(');\\',NULL,NULL),
	('\\',NULL,NULL),
	('CREATE TABLE listings (\\',NULL,NULL),
	('    id INT PRIMARY KEY AUTO_INCREMENT','\\',NULL),
	('    user_id INT','\\',NULL),
	('    vehicle_id INT','\\',NULL),
	('    title VARCHAR(255)','\\',NULL),
	('    description TEXT','\\',NULL),
	('    status ENUM(''active''',' ''inactive'')','\\'),
	('    created_at TIMESTAMP','\\',NULL),
	('    updated_at TIMESTAMP','\\',NULL),
	('    FOREIGN KEY (user_id) REFERENCES users(id)','\\',NULL),
	('    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)\\',NULL,NULL),
	(');\\',NULL,NULL),
	('\\',NULL,NULL),
	('CREATE TABLE comments (\\',NULL,NULL),
	('    id INT PRIMARY KEY AUTO_INCREMENT','\\',NULL),
	('    user_id INT','\\',NULL),
	('    listing_id INT','\\',NULL),
	('    content TEXT','\\',NULL),
	('    created_at TIMESTAMP','\\',NULL),
	('    updated_at TIMESTAMP','\\',NULL),
	('    FOREIGN KEY (user_id) REFERENCES users(id)','\\',NULL),
	('    FOREIGN KEY (listing_id) REFERENCES listings(id)\\',NULL,NULL),
	(');\\',NULL,NULL),
	('\\',NULL,NULL),
	('CREATE TABLE images (\\',NULL,NULL),
	('    id INT PRIMARY KEY AUTO_INCREMET\\',NULL,NULL),
	(' listing_id INT','\\',NULL),
	('    file_path VARCHAR(255)','\\',NULL),
	('    created_at TIMESTAMP','\\',NULL),
	('    updated_at TIMESTAMP','\\',NULL),
	('    FOREIGN KEY (listing_id) REFERENCES listings(id)\\',NULL,NULL),
	(');}',NULL,NULL);
